import '@/styles/globals.css';
import GlassPane from '@/components/GlassPane'; 
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets:['latin'],
  variable: "--font-inter",
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthRootLayout({ children }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <head />
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {children}
        </GlassPane>
      </body>
    </html>
  );
}

 